version: '3'
services:
    neo4j:
        image: neo4j:latest
        ports:
          - "7474:7474"
          - "7687:7687"
        env_file:
            - ./docker/neo4j/.env
    command:
         build: ./command-service
         image: command-service:latest
         ports:
             - 8090:8090
         env_file:
            - ./docker/spring/.env
    processor:
         build: ./processor-service
         image: processor-service:latest
         ports:
             - 8091:8091
         env_file:
            - ./docker/spring/.env