version: '3'
services:
    kafka-stack:
        image: landoop/fast-data-dev:latest
        environment:
            - FORWARDLOGS=0
            - RUNTESTS=0
        ports:
            - 3030:3030
    neo4j:
        image: neo4j:latest
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_dbms_shell_enabled=true
            - NEO4J_AUTH=neo4j/adidas
    command:
        build: .
        image: adidas-challenge-services:latest
        command: java -jar /app/command-service.jar
        depends_on:
            - kafka-stack
        ports:
            - 8090:8080
        env_file:
            - .dockerenv
    processor:
        build: .
        image: adidas-challenge-services:latest
        command: java -jar /app/processor-service.jar
        depends_on:
            - kafka-stack
            - neo4j
        ports:
            - 8091:8080
        env_file:
            - .dockerenv
    query:
        build: .
        image: adidas-challenge-services:latest
        command: java -jar /app/query-service.jar
        depends_on:
            - kafka-stack
            - neo4j
        ports:
            - 8092:8080
        env_file:
            - .dockerenv