spring:
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: 192.168.99.100:2181
          brokers: 192.168.99.100:9092
      bindings:
        cities-in:
          destination: cities
          contentType: application/json
        cities-out:
          destination: cities
          contentType: application/json
  jpa:
    show-sql: true
    ddl-auto: update
    generate-ddl: true
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/adidas?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      sql-script-encoding: UTF-8
      username: adidas
      password: adidas
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: GMT
    default-property-inclusion: NON_NULL
server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
        min-response-size: 1024
doc:
  api:
    name: Adidas Challange Test
    description: Adidas Challange Test
    version: 1.0.0
    maintainer:
      name: Felipe Passos
      email: felipe.espitalher@gmail.com
flyway:
  enabled: true
logging:
  file: adidas.log
  level:
    org:
      apache: INFO