neo4j:
  ogm:
    URI: bolt://localhost:7687
    username: neo4j
    password: adidas
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: GMT
    default-property-inclusion: NON_NULL
server:
  port: 8092
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024
doc:
  api:
    name: Adidas Challange Test
    description: Adidas Challange Test
    version: 1.0.0
    maintainer:
      name: Felipe Passos
      email: felipe.espitalher@gmail.com
logging:
  file: adidas.log
  level:
    org:
      apache: INFO
